### ISSUE TITLE
Suddenly getting Type Error

### ISSUE THREAD

**Issue by shubhammapara** [Virtualstock/behave-testrail-reporter#151]
`Exception TypeError: string indices must be integers
Traceback (most recent call last):
  File "/home/circleci/project/venv/bin/behave", line 11, in <module>
    sys.exit(main())
  File "/home/circleci/project/venv/lib/python3.6/site-packages/behave/__main__.py", line 183, in main
    return run_behave(config)
  File "/home/circleci/project/venv/lib/python3.6/site-packages/behave/__main__.py", line 127, in run_behave
    failed = runner.run()
  File "/home/circleci/project/venv/lib/python3.6/site-packages/behave/runner.py", line 804, in run
    return self.run_with_paths()
  File "/home/circleci/project/venv/lib/python3.6/site-packages/behave/runner.py", line 824, in run_with_paths
    return self.run_model()
  File "/home/circleci/project/venv/lib/python3.6/site-packages/behave/runner.py", line 640, in run_model
    reporter.feature(feature)
  File "/home/circleci/project/venv/lib/python3.6/site-packages/behave_testrail_reporter/testrail_reporter.py", line 101, in feature
    self.process_scenario_outline(scenario)
  File "/home/circleci/project/venv/lib/python3.6/site-packages/behave_testrail_reporter/testrail_reporter.py", line 295, in process_scenario_outline
    self.process_scenario(scenario)
  File "/home/circleci/project/venv/lib/python3.6/site-packages/behave_testrail_reporter/testrail_reporter.py", line 265, in process_scenario
    self._load_test_cases_for_project(testrail_project)
  File "/home/circleci/project/venv/lib/python3.6/site-packages/behave_testrail_reporter/testrail_reporter.py", line 204, in _load_test_cases_for_project
    project.cases = {str(case[u"id"]): case for case in cases}
  File "/home/circleci/project/venv/lib/python3.6/site-packages/behave_testrail_reporter/testrail_reporter.py", line 204, in <dictcomp>
    project.cases = {str(case[u"id"]): case for case in cases}
TypeError: string indices must be integers`

All of sudden from today it started giving Type error, any solution to this?

**Comment by miclea-eloquentix** [comment]
The issue is that testrail changed the response on their api, get_cases no longer returns a list of al cases but an object containing pagination info and cases property which is a list of max 250 cases.
This is a breaking change, so behave-testrail-reporter is useless until fixed

**Comment by shubhammapara** [comment]
Oh gotcha! Thanks for the update! @miclea-eloquentix

**Comment by BernardoSilva** [comment]
Thanks for reporting @shubhammapara and for the investigation @miclea-eloquentix .
A bit weird why would Testrail break compatibility on a versioned api... :thinking: "v2" is a bit pointless if they do not use versioning for this stuff.
Will try and get something to address this when I have a moment.
